apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
spec:
  serviceName: postgresql-service
  replicas: 1
  template:
    metadata:
      app: postgresql-app
    spec:
      containers:
        - name: postgresql-container
          image: postgres:alpine

          env:
            - name: PGPASSFILE
              value: "/run/secrets/postgresql/password.txt"

          ports:
            - containerPort: 5432
              name: postgresql-cli

          volumeMounts:
            - mountPath: "/data/db"
              name: postgresql-pvc
            - mountPath: "/run/secrets/postgresql"
              name: postgresql-secret-volume
              readOnly: true

      volumes:
        - name: postgresql-secret-volume
          secret:
            secretName: postgresql-secret
            optional: false

  selector:
    matchLabels:
      app: postgresql-app

  volumeClaimTemplates:
    - metadata:
        name: postgresql-pvc
    - spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
