version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: ./bin/node.dockerfile
    container_name: app
    hostname: app
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "5173:5173"

  nginx-proxy:
    build:
      context: ./
      dockerfile: ./bin/nginx.dockerfile
    container_name: nginx-proxy
    hostname: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  app:
  nginx-proxy: