port: 8080

accountService: {
  host: localhost:44042,
  timeout: "1h"
}

authService: {
  host: localhost:44041,
  timeout: "1h"
}

chatService: {
  host: localhost:44044,
  timeout: "1h"
}

groupService: {
  host: localhost:44043,
  timeout: "1h"
}